### ISSUE TITLE
Enabling cross cloud-provider image import.

### ISSUE THREAD

**Issue by iv1111** [ManageIQ/manageiq-providers-ibm_cloud#180]
Location: UI, API
Form: Add

current type: 
API state:
Need info

PM Input:
Comments: 

This currently open [RFE 7675](https://github.com/ManageIQ/manageiq-ui-classic/issues/7675) is **blocking** us from proceeding.

Additionally, we need to decide on architecture of the API handler in the manageiq-api, namely 
how we implement the "supports?" method for validating whether a given workflow is supported.
ManageIQ/manageiq-api#1021

Ems common

imported status: NOT ASSIGNED

### ManageIQ base, API, and UI
- [x]  Documentation describing steps necessary in order to try out the image import workflow (https://github.com/ManageIQ/manageiq-documentation/pull/1618)
- [x] new POST API method allowing import of images from one provider into another (ManageIQ/manageiq-api#1021)
- [x] adding support for importing images between providers (ManageIQ/manageiq#21106)
- [x] adding 'import_image' API-feature to miq_product_features.yml (ManageIQ/manageiq#21112)
- [x] Allow the addition of standalone object storage managers (ManageIQ/manageiq-ui-classic#7675)
    - [x] Combine Block/Object Mixins into StorageManager (ManageIQ/manageiq#21213)
    - [x] Update API product features (ManageIQ/manageiq-api#1041)
    - [x] Schema migration for product features (ManageIQ/manageiq-schema#581)
    - [x] Combine block and object storage and refactor storage submenu (ManageIQ/manageiq-ui-classic#7746)
 

### PowerVC Provider
- [x] New IBM PowerVC provider ([ManageIQ/manageiq-providers-ibm_power_vc](https://github.com/ManageIQ/manageiq-providers-ibm_power_vc))
- [x] PowerVC decorator (ManageIQ/manageiq-decorators#49) (needs a better icon)
- [x] Restructured registration form (ManageIQ/manageiq-providers-ibm_power_vc#15)

### IBM Cloud Provider
- [x] Image Import Functionality for PowerVS <-- PowerVC (ManageIQ/manageiq-providers-ibm_cloud#215)
- [x]  Add new IBM Cloud-Object-Storage provider (ManageIQ/manageiq-providers-ibm_cloud#159)

----

We are working on an interesting use-case of allowing users to import images from one cloud provider into another.
An example of how this might look like can be seen below:

![image_import](https://user-images.githubusercontent.com/69972357/113318208-841a2d80-9310-11eb-9a9d-3ce43f639a67.png)

As a first workflow of this kind we're currently implementing a scenario of importing images from PowerVC into PowerVS. Although concentrating on this parricular case, we try to keep the Manageiq Base, API and other changes as generic as possible so that other vendors would be able to reuse our api and take our implementation as an example. 

The form above is just an example for the PowerVS <-- PowerVC case. If one implements the import workflow for some other provider pair, the UI-form might look differently. However, three parameters of this workflow will have to stay fixed: 

- Destination Provider Id
- Source Provider Id 
- Source Image Id

----

**UI-Form:**

Custom UI form has to be implemented by a given destination provider, which let user import images into it. In simple case it will have only the three parameters above.

**API Module:**

This PR introduces the new API method "import_image"
https://github.com/ManageIQ/manageiq-api/pull/1021

Here we've defined the API handler, which accepts the following parameters in the body:

`{"action": "import", "dst_provider_id": 10, "src_provider_id": 14, "src_image_id": 23 }'`

The pending discussion is currently regarding the proper way we should use "supports?" in the handler for parameter validation.

The URL path is: _/api/cloud_templates_

**Base Repository**

Here we have added the new feature declaration and some default handlers of the API action to the Template class.
The API action handler adds a queue task and the actual import method has to be implemented in the corresponding destination provider. In case of PowerVS <--- PowerVC workflow our implementaiton of the provider specific image_import handler runs an ansible playbook, which performs the actual task of importing.

https://github.com/ManageIQ/manageiq/pull/21106

https://github.com/ManageIQ/manageiq/pull/21112

----

**PowerVC Cloud Provider**

As we would later implement the reverse direction, namely PowerVC <-- PowerVS import, we are in the process of extending the existing OpenStack provider to create our own PowerVC cloud provider, which we can customize accordingly. PowerVC is based on OpenStack and therefore we just extend the existing Openstack provider.

https://github.com/ManageIQ/manageiq-providers-ibm_power_vc

**Power Virtual Servers Provider**

Following is the branch with the import handler implementation of the PowerVS provider. It represents the destination provider in the PowerVS <--- PowerVC scenario. Currently work in progress.

[ ManageIQ/manageiq-providers-ibm_cloud /215](https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/215)

**IBM Cloud Object Storage**

This doesn't have to do with image import in a generic sense but is needed in our PowerVS <----> PowerVC scenarios only (both directions).  In both directions a transient storage over IBM COS is used for the import. 

We're currently unable to register our object storage provider, because the registration form for this kind of providers is currently disabled in MIQ. Here is the corresponding RFE that addresses this issue.
https://github.com/ManageIQ/manageiq-ui-classic/issues/7675

Here lies our new object storage provider: https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/159

**Comment by iv1111** [comment]
@agrare @Fryguy  I thought we could start the discussion by deciding on how to proceed with checking the support of import workflow by the source and destination providers in the API handler. That seems to be the only thing that keeps the corresp. PR open.

**Comment by agrare** [comment]
:+1: can you give some examples of what you'll need to check for to determine support for import?

**Comment by iv1111** [comment]
**For PowerVC:**

- import session directory exists on a PVC server
- directory has enough space in it (GBs are required)
- PVC cmd-line app credentials are available in an .rc file
- python virtual environment exists in the session directory
- python virtual environment contains certain packages
- (maybe something more if I've forgotten anything)

Most can be probably automated using ansible it's a task of its own.

---
In more general case, imagine PowerVC <--- OpenStack import or even PowerVC A <---- PowerVC B.
In these scenarios one needs server preparations both on sender and on the receiver.

Therefore, in general, some sort of check like this is imaginable:

`ok1 = src_provider.supports_export_to?(dst_provider)`
`ok2 = dst_provider.supports_import_from?(src_provider)`

Looking at it in a general way, in some scenarios, _supports_export_to_ and _supports_import_from_ will look very simple, just checking the _dst_provider_ and _src_provider_ class names respectively and returning true/false.

In other cases, one would need implement logic in both methods to make sure the workflow is possible.

----
Another much more simple but crude solution is to let it run without complicated checks like that and it would eventually fail with an error indicating the reason.

**Comment by agrare** [comment]
https://github.com/ManageIQ/manageiq/pull/21340 allows for pluggable job dispatchers

**Comment by agrare** [comment]
@iv1111 I see the only open checklist item here has been closed (not merged).  Can this feature be closed out as implemented or is there still more to go here?

**Comment by iv1111** [comment]
@agrare I have closed the PR without merging but I have a different branch for the documentation (locally). I will create a new PR later tomorrow, which will contain the final documentation and set it for a review. So, this Issue isn't closed yet.

I will remove the outdated #1586 from the Issue description.

**Comment by iv1111** [comment]
@agrare the Issue can be closed, thanks for the docs merge
