### ISSUE TITLE
[MORPHY] IBM Cloud PowerVS Provider Enhancements

### ISSUE THREAD

**Issue by agrare** [ManageIQ/manageiq-providers-ibm_cloud#269]
- [x] Reporting Enhancements
    - [x] Create virtual columns for Power related attributes
        - ManageIQ/manageiq#21306
        - ManageIQ/manageiq#21350
    - [x] Add report templates for PowerVS/PowerVC #251
- [x] PowerVC Enhancements
    - [x] PowerVC provider documentation updates (fix capabilities matrix) https://github.com/ManageIQ/manageiq-documentation/issues/1563
    - [x] Create new PowerVC provider (subclass of OpenStack provider) - https://github.com/ManageIQ/manageiq/issues/21098
- [x] Collect available `CloudVolumeType`'s from [PCloudStorageCapacity API](https://cloud.ibm.com/apidocs/power-cloud#pcloud-storagecapacity-types-getall) https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/237
- [x] Provisioning: Add software license fields #246
- [x] Targeted Collections #250

**Comment by agrare** [comment]
All PRs backported, moving to `Morphy`
